# frozen_string_literal: true

# NOTE: Common constant used in customers gemspec's
require "find"

# Intentionally empty Gemfile to allow running `bundle exec` on native helpers
# without it trying to resolve a customers `Gemfile` dependencies
